name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - name: Run check
        run: cargo check
      - name: Run test
        run: cargo test
      - uses: messense/maturin-action@v1
        with:
          command: build
          args: --release
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: make virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install pytest
      - uses: messense/maturin-action@v1
        with:
          command: develop
          args: --release
      - name: run pytest
        run: |
          python3 -m pytest        
